/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Employees;

import DataBase.get_all_procs;
import DataBase.get_procs;
import DataBase.upd_procs;
import Models.campus;
import Models.employee;
import Models.post;
import Models.status;
import Utilities.extra_methods;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * 
 * @author Lucas A. Oviedo Castro 
 * <p>
 * Last Modify Date: 06/02/2023.
 * By: Lucas A. Oviedo Castro 
 * <p>
 * JPanel with the View to check employee company information
 */
public class companyInfo extends javax.swing.JPanel {
        DefaultTableModel dtm = new DefaultTableModel();
    
        ArrayList<campus> allCampus;
        ArrayList<post> allPosts;
        ArrayList<status> allStatus;
        int countDays = 0;
        
        employee selectedEmp;
        
    /**
     * View Constructor
     * @param selectedEmp ArrayList of employees - the selected employees
     * @throws ClassNotFoundException if the class is not found
     * @throws SQLException if there is a problem during data collection
     */
    public companyInfo(employee selectedEmp) throws SQLException, ClassNotFoundException {
        initComponents();
        this.selectedEmp = selectedEmp;
        allCampus = get_all_procs.get_all_campuses();
        allPosts = get_all_procs.get_all_post();
        allStatus = get_all_procs.get_all_status();
        
        campusCombo.removeAllItems();
        postCombo.removeAllItems();
        statusCombo.removeAllItems();
        
        String[] header = new String[]{"Fecha de entrada", "Fecha de vacaciones", "Contador de dias"};
        dtm.setColumnIdentifiers(header);
        holidayTable.setModel(dtm);  
        
        for(campus camp : allCampus){
            campusCombo.addItem(camp.getName_campus());
        }
        
        for(post pt : allPosts){
            postCombo.addItem(pt.getName_post());
        }
        
        for(status st : allStatus){
            statusCombo.addItem(st.getName_status());
        }
        
        updateFields();
    }
    
    /**
     * Update Combo Boxes and the view table
     * @throws SQLException
     * @throws ClassNotFoundException 
     */
    private void updateFields() throws SQLException, ClassNotFoundException{
        selectedEmp = get_procs.get_employee(selectedEmp.getId_employee());
        entryDateChooser.setDate(selectedEmp.getEntry_date());
        campusCombo.setSelectedItem(get_procs.get_campus(selectedEmp.getId_campus()).getName_campus());
        postCombo.setSelectedItem(get_procs.get_post(selectedEmp.getId_post()).getName_post());
        statusCombo.setSelectedItem(get_procs.get_status(selectedEmp.getId_status()).getName_status());
        
        extra_methods.clearTable(holidayTable, dtm);
        dtm.addRow(new Object[]{
            selectedEmp.getEntry_date(), selectedEmp.getHoliday(), selectedEmp.getDay_count()
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        holidayTable = new javax.swing.JTable();
        subsDayButton = new javax.swing.JButton();
        addDayButton = new javax.swing.JButton();
        statusCombo = new javax.swing.JComboBox<>();
        campusCombo = new javax.swing.JComboBox<>();
        postCombo = new javax.swing.JComboBox<>();
        entryDateChooser = new com.toedter.calendar.JDateChooser();
        refreshImage = new Utilities.image_avatar();
        commentsImage = new Utilities.image_avatar();

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(1260, 700));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Estado");

        jLabel2.setText("Fecha de Entrada");

        jLabel3.setText("Puesto");

        jLabel4.setText("Sede");

        holidayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(holidayTable);

        subsDayButton.setText("-");
        subsDayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subsDayButtonMouseClicked(evt);
            }
        });
        subsDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsDayButtonActionPerformed(evt);
            }
        });

        addDayButton.setText("+");
        addDayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDayButtonMouseClicked(evt);
            }
        });

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        campusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        postCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        refreshImage.setBorderSize(0);
        refreshImage.setBorderSpace(0);
        refreshImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/optionsPerPanel/refreshImage.png"))); // NOI18N
        refreshImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshImageMouseExited(evt);
            }
        });

        commentsImage.setBorderSize(0);
        commentsImage.setBorderSpace(1);
        commentsImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/optionsPerPanel/commentsImage.png"))); // NOI18N
        commentsImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentsImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commentsImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commentsImageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(commentsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subsDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(156, 156, 156)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(postCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jLabel1))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(campusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(entryDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(commentsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(addDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(subsDayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(refreshImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subsDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsDayButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subsDayButtonActionPerformed

    private void addDayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDayButtonMouseClicked
        holidayTable.setValueAt((int) holidayTable.getValueAt(0, 2)+1, 0, 2);
        countDays += 1;
        System.out.println(countDays);
    }//GEN-LAST:event_addDayButtonMouseClicked

    private void subsDayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subsDayButtonMouseClicked
        holidayTable.setValueAt((int) holidayTable.getValueAt(0, 2)-1, 0, 2);
        countDays -= 1;
        System.out.println(countDays);

    }//GEN-LAST:event_subsDayButtonMouseClicked

    private void refreshImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshImageMouseClicked
            try {
                boolean changes = false;
                if(!get_procs.get_campus(selectedEmp.getId_campus()).getName_campus().equals(campusCombo.getSelectedItem())){
                    if(extra_methods.confirmChanges(content, changes)){
                        String selectedCampusName = (String) campusCombo.getSelectedItem();
                        int selectedCampusId = get_procs.get_campus_by_name(selectedCampusName).getId_campus();
                        upd_procs.update_employee_campus(selectedCampusId, selectedEmp.getId_employee());       
                        changes = true;
                    }
                }
                if(!get_procs.get_post(selectedEmp.getId_post()).getName_post().equals(postCombo.getSelectedItem())){
                    if(extra_methods.confirmChanges(content, changes)){
                        String selectedPostName = (String) postCombo.getSelectedItem();
                        int selectedPostId = get_procs.get_post_by_name(selectedPostName).getId_post();
                        upd_procs.update_employee_post(selectedPostId, selectedEmp.getId_employee());
                        changes = true;
                    }
                }
                if(!get_procs.get_status(selectedEmp.getId_status()).getName_status().equals(statusCombo.getSelectedItem())){
                    if(extra_methods.confirmChanges(content, changes)){
                        String selectedStatusName = (String) statusCombo.getSelectedItem();
                        int selectedStatusId = get_procs.get_status_by_name(selectedStatusName).getId_status();
                        upd_procs.update_employee_status(selectedStatusId, selectedEmp.getId_employee());
                        changes = true;
                    }
                }
                if(!selectedEmp.getEntry_date().equals(entryDateChooser.getDate())){
                    if(extra_methods.confirmChanges(content, changes)){
                        long d = entryDateChooser.getDate().getTime();
                        java.sql.Date entryDate = new java.sql.Date(d);
                        upd_procs.update_employee_entry_date(entryDate, selectedEmp.getId_employee());
                        changes = true;
                    }
                }
                if(countDays != 0){
                    if(extra_methods.confirmChanges(content, changes)){
                        upd_procs.update_employee_day_count(selectedEmp.getDay_count() + countDays, selectedEmp.getId_employee());
                        changes = true;
                    }
                }
                updateFields();
                extra_methods.changesAdvice(content, changes);
                countDays = 0;
                
            } catch (SQLException ex) {
                Logger.getLogger(companyInfo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(companyInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_refreshImageMouseClicked

    private void refreshImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshImageMouseEntered
        extra_methods.showSelectedOption(refreshImage, 995, 420);
    }//GEN-LAST:event_refreshImageMouseEntered

    private void refreshImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshImageMouseExited
        extra_methods.resetSelectedOption(refreshImage, 1000, 420);
    }//GEN-LAST:event_refreshImageMouseExited

    private void commentsImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentsImageMouseClicked
    try {
        commentsFrame p = new commentsFrame(selectedEmp);
        p.setSize(650,500);
        p.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(companyInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(companyInfo.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_commentsImageMouseClicked

    private void commentsImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentsImageMouseEntered
        extra_methods.showSelectedOption(commentsImage, 905, 420);
    }//GEN-LAST:event_commentsImageMouseEntered

    private void commentsImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentsImageMouseExited
        extra_methods.resetSelectedOption(commentsImage, 910, 420);
    }//GEN-LAST:event_commentsImageMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDayButton;
    private javax.swing.JComboBox<String> campusCombo;
    private Utilities.image_avatar commentsImage;
    private javax.swing.JPanel content;
    private com.toedter.calendar.JDateChooser entryDateChooser;
    private javax.swing.JTable holidayTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> postCombo;
    private Utilities.image_avatar refreshImage;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JButton subsDayButton;
    // End of variables declaration//GEN-END:variables
}
