/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Employees;

import DataBase.get_all_procs;
import DataBase.get_procs;
import DataBase.ins_procs;
import DataBase.upd_procs;
import Models.canton;
import Models.district;
import Models.employee;
import Models.phone;
import Models.province;
import Utilities.extra_methods;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * 
 * @author Lucas A. Oviedo Castro 
 * <p>
 * Last Modify Date: 06/02/2023.
 * By: Lucas A. Oviedo Castro 
 * <p>
 * JPanel with the View to check employee contact information
 */
public class contactInfo extends javax.swing.JPanel {
        DefaultTableModel dtm = new DefaultTableModel();
        ArrayList<province> selectedProvinces;
        ArrayList<canton> selectedCantons;
        ArrayList<district> selectedDistricts;
        ArrayList<phone> employeePhones;
        
        employee selectedEmp;
        
    /**
     * View Constructor
     * @param selectedEmp ArrayList of employees - the selected employees
     * @throws ClassNotFoundException if the class is not found
     * @throws SQLException if there is a problem during data collection
     */
    public contactInfo(employee selectedEmp) throws SQLException, ClassNotFoundException {
        initComponents();
        this.selectedEmp = selectedEmp;
        
        provinceCombo.removeAllItems();
        
        selectedProvinces = get_all_procs.get_all_provinces();
        for(province prov : selectedProvinces){
            provinceCombo.addItem(prov.getName_province());
        }
        
        provinceComboChanges();
        cantonComboChanges();
        updateFields();

        String[] header = new String []{"Número de teléfono", "Tipo de teléfono"};
        dtm.setColumnIdentifiers(header);
        phonesTable.setModel(dtm);
        employeePhones = get_procs.get_phone_by_emp(selectedEmp.getId_employee());
        for(phone ph : employeePhones){
            dtm.addRow(new Object[] {ph.getNumber_phone(), get_procs.get_ph_category(ph.getId_phone_category()).getDescription_category()});
        }
        
    }
    
    /**
     * Update Combo Boxes and Text Fields
     * @throws SQLException
     * @throws ClassNotFoundException 
     */
    private void updateFields() throws SQLException, ClassNotFoundException{
        selectedEmp = get_procs.get_employee(selectedEmp.getId_employee());
        districtCombo.setSelectedItem(get_procs.get_district(selectedEmp.getId_district()).getName_district());
        cantonCombo.setSelectedItem(get_procs.get_canton(get_procs.get_district(selectedEmp.getId_district()).getId_canton()).getName_canton());
        provinceCombo.setSelectedItem(get_procs.get_province(get_procs.get_canton(get_procs.get_district(selectedEmp.getId_district()).getId_canton()).getId_province()).getName_province());
        mailField.setText(get_procs.get_email_by_emp(selectedEmp.getId_employee()).getAddress_email());
    }
    
    /**
     * Update Canton Combo Box
     * @throws SQLException
     * @throws ClassNotFoundException 
     */
    private void provinceComboChanges() throws SQLException, ClassNotFoundException{
        cantonCombo.removeAllItems();
        
        String nameSelectedProvince = (String) provinceCombo.getSelectedItem();
        int idSelectedProvince = get_procs.get_province_by_name(nameSelectedProvince).getId_province();
        selectedCantons = get_procs.get_cantons_by_province(idSelectedProvince);
                
        for(canton cant : selectedCantons){
            cantonCombo.addItem(cant.getName_canton());
        }
    }
    
    /**
     * Update District Combo Box
     * @throws SQLException
     * @throws ClassNotFoundException 
     */
    private void cantonComboChanges() throws SQLException, ClassNotFoundException{
        districtCombo.removeAllItems();
        
        String nameSelectedCanton = (String) cantonCombo.getSelectedItem();
        int idSelectedCanton = get_procs.get_canton_by_name(nameSelectedCanton).getId_canton();
        selectedDistricts = get_procs.get_districts_by_canton(idSelectedCanton);
        
        for(district dist : selectedDistricts){
            districtCombo.addItem(dist.getName_district());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        mailField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        phonesTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        districtCombo = new javax.swing.JComboBox<>();
        provinceCombo = new javax.swing.JComboBox<>();
        cantonCombo = new javax.swing.JComboBox<>();
        refreshImage = new Utilities.image_avatar();

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(1260, 700));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        mailField.setBorder(null);

        jLabel1.setText("Distrito");

        jLabel2.setText("Provincia");

        jLabel3.setText("Cantón");

        phonesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(phonesTable);

        jLabel4.setText("Correo");

        jLabel5.setText("Teléfonos");

        districtCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        provinceCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        provinceCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                provinceComboItemStateChanged(evt);
            }
        });
        provinceCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                provinceComboMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                provinceComboMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                provinceComboMouseReleased(evt);
            }
        });

        cantonCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cantonCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cantonComboItemStateChanged(evt);
            }
        });

        refreshImage.setBorderSize(0);
        refreshImage.setBorderSpace(0);
        refreshImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/optionsPerPanel/refreshImage.png"))); // NOI18N
        refreshImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshImageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provinceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(districtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(refreshImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(provinceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(cantonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(districtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(refreshImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mailField.getAccessibleContext().setAccessibleName("");
        jLabel4.getAccessibleContext().setAccessibleName("");
        jLabel5.getAccessibleContext().setAccessibleName("");
        jSeparator1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void provinceComboMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_provinceComboMouseReleased

    }//GEN-LAST:event_provinceComboMouseReleased

    private void provinceComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_provinceComboMouseClicked

    }//GEN-LAST:event_provinceComboMouseClicked

    private void provinceComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_provinceComboMousePressed

    }//GEN-LAST:event_provinceComboMousePressed

    private void provinceComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_provinceComboItemStateChanged
            try {
                provinceComboChanges();
            } catch (SQLException ex) {
                Logger.getLogger(contactInfo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(contactInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_provinceComboItemStateChanged

    private void cantonComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cantonComboItemStateChanged
            try {
                cantonComboChanges();
            } catch (SQLException ex) {
                Logger.getLogger(contactInfo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(contactInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_cantonComboItemStateChanged

    private void refreshImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshImageMouseClicked
            try {
                boolean isChanged = false;
                if(!get_procs.get_district(selectedEmp.getId_district()).getName_district().equals(districtCombo.getSelectedItem())){
                    if(extra_methods.confirmChanges(content, isChanged)){
                        String selectedDistrictName = (String) districtCombo.getSelectedItem();
                        int selectedDistrictId = get_procs.get_district_by_name(selectedDistrictName).getId_district();
                        upd_procs.update_employee_district(selectedDistrictId, selectedEmp.getId_employee());
                        isChanged = true;
                    } 
                }
                if(!mailField.getText().equals(get_procs.get_email_by_emp(selectedEmp.getId_employee()).getAddress_email())){
                    if(extra_methods.isValidMail(content, mailField.getText())){
                        if(extra_methods.confirmChanges(content, isChanged)){
                            if(get_procs.get_email_by_emp(selectedEmp.getId_employee()).getAddress_email() == null){
                                ins_procs.insert_email(mailField.getText(), selectedEmp.getId_employee());
                                isChanged = true;
                            }else{
                               upd_procs.update_email_address(mailField.getText(), get_procs.get_email_by_emp(selectedEmp.getId_employee()).getId_email()); 
                               isChanged = true;
                            }
                        }
                    }
                }
                updateFields();
                extra_methods.changesAdvice(content, isChanged);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(contactInfo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(contactInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_refreshImageMouseClicked

    private void refreshImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshImageMouseEntered
        extra_methods.showSelectedOption(refreshImage, 995, 420);
    }//GEN-LAST:event_refreshImageMouseEntered

    private void refreshImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshImageMouseExited
        extra_methods.resetSelectedOption(refreshImage, 1000, 420);
    }//GEN-LAST:event_refreshImageMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cantonCombo;
    private javax.swing.JPanel content;
    private javax.swing.JComboBox<String> districtCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField mailField;
    private javax.swing.JTable phonesTable;
    private javax.swing.JComboBox<String> provinceCombo;
    private Utilities.image_avatar refreshImage;
    // End of variables declaration//GEN-END:variables
}
