/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Employees;

import DataBase.get_all_procs;
import DataBase.get_procs;
import Models.campus;
import Models.post;
import Models.status;
import Utilities.extra_methods;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * 
 * @author Lucas A. Oviedo Castro 
 * <p>
 * Last Modify Date: 06/02/2023.
 * By: Lucas A. Oviedo Castro 
 * <p>
 * JPanel with the View to insert employee company information (2/3).
 */
public class insertCompanyPanel extends javax.swing.JPanel {
        ArrayList<Object> infoList;
        ArrayList<post> allPosts; 
        ArrayList<campus> allCampuses;
        ArrayList<status> allStatus;
        java.sql.Date entryDate;

     /**
     * View Constructor
     * @param personalInfoList ArrayList of objects - all the employee personal information to insert
     * @throws ClassNotFoundException if the class is not found
     * @throws SQLException if there is a problem during data collection
     */
    public insertCompanyPanel(ArrayList<Object> personalInfoList) throws SQLException, ClassNotFoundException {
        initComponents();
        infoList = personalInfoList;
        campusCombo.removeAllItems();
        postCombo.removeAllItems();
        statusCombo.removeAllItems();
        
        allPosts = get_all_procs.get_all_post();
        allCampuses = get_all_procs.get_all_campuses();
        allStatus = get_all_procs.get_all_status();
        
        for(post pt : allPosts){
            postCombo.addItem(pt.getName_post());
        }
        for(campus cp : allCampuses){
            campusCombo.addItem(cp.getName_campus());
        }
        for(status st : allStatus){
            statusCombo.addItem(st.getName_status());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        postCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        entryDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campusCombo = new javax.swing.JComboBox<>();
        statusCombo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        nextImage = new Utilities.image_avatar();

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(1260, 700));

        postCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        postCombo.setBorder(null);

        jLabel8.setText("Posición");

        entryDateChooser.setDateFormatString("dd MM YY");
        entryDateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entryDateChooserMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                entryDateChooserMouseReleased(evt);
            }
        });

        jLabel14.setText("Fecha Entrada");

        jLabel9.setText("Campus");

        campusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        campusCombo.setBorder(null);

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusCombo.setBorder(null);

        jLabel15.setText("Estado");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        nextImage.setBorderSize(0);
        nextImage.setBorderSpace(0);
        nextImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/optionsPerPanel/nextImage.png"))); // NOI18N
        nextImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextImageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(nextImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(entryDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(postCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(campusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel15)
                .addGap(6, 6, 6)
                .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(nextImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entryDateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryDateChooserMouseClicked

    }//GEN-LAST:event_entryDateChooserMouseClicked

    private void entryDateChooserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryDateChooserMouseReleased

    }//GEN-LAST:event_entryDateChooserMouseReleased

    private void nextImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextImageMouseClicked
    try {
        if(entryDateChooser.getDate() != null){
            String post = (String) postCombo.getSelectedItem();
            int idPost = get_procs.get_post_by_name(post).getId_post();
            String campus = (String) campusCombo.getSelectedItem();
            int idCampus = get_procs.get_campus_by_name(campus).getId_campus();
            String status = (String) statusCombo.getSelectedItem();
            int idStatus = get_procs.get_status_by_name(status).getId_status();

            Date date = entryDateChooser.getDate();
            long d = date.getTime();
            entryDate = new java.sql.Date(d);

            ArrayList<Object> companyInfoList = new ArrayList();
            companyInfoList.add(idPost);
            companyInfoList.add(idCampus);
            companyInfoList.add(idStatus);
            companyInfoList.add(entryDate);

            insertContactPanel p = new insertContactPanel(infoList, companyInfoList);
            extra_methods.showPanel(p, content);
        }else{
            JOptionPane.showMessageDialog(content, "Todos los datos de este panel son obligatorios", "ERROR: Faltan campos de llenar", JOptionPane.ERROR_MESSAGE);
        }
       
                
    } catch (SQLException ex) {
        Logger.getLogger(insertCompanyPanel.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(insertCompanyPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_nextImageMouseClicked

    private void nextImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextImageMouseEntered
        extra_methods.showSelectedOption(nextImage, 995, 420);
    }//GEN-LAST:event_nextImageMouseEntered

    private void nextImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextImageMouseExited
        extra_methods.resetSelectedOption(nextImage, 1000, 420);
    }//GEN-LAST:event_nextImageMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> campusCombo;
    private javax.swing.JPanel content;
    private com.toedter.calendar.JDateChooser entryDateChooser;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private Utilities.image_avatar nextImage;
    private javax.swing.JComboBox<String> postCombo;
    private javax.swing.JComboBox<String> statusCombo;
    // End of variables declaration//GEN-END:variables
}
