/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Employees;

import DataBase.get_all_procs;
import DataBase.get_procs;
import DataBase.ins_procs;
import Models.canton;
import Models.district;
import Models.phone_category;
import Models.province;
import Utilities.extra_methods;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * 
 * @author Lucas A. Oviedo Castro 
 * <p>
 * Last Modify Date: 06/02/2023.
 * By: Lucas A. Oviedo Castro 
 * <p>
 * JPanel with the View to insert employee contact information
 * At this panel the employee will finally added to Employee Table in mySQL (3/3). 
 */
public class insertContactPanel extends javax.swing.JPanel {
        ArrayList<Object> infoList;
        ArrayList<Object> companyList;
        ArrayList<province> allProvinces;
        ArrayList<canton> allCantons;
        ArrayList<district> allDistricts;
        ArrayList<phone_category> allCategories;
        
     /**
     * View Constructor
     * @param personalInfoList ArrayList of objects - all the employee personal information to insert
     * @param companyInfoList ArrayList of objects - all the employee company information to insert
     * @throws ClassNotFoundException if the class is not found
     * @throws SQLException if there is a problem during data collection
     */
    public insertContactPanel(ArrayList<Object> personalInfoList, ArrayList<Object> companyInfoList) throws SQLException, ClassNotFoundException {
        initComponents();
        infoList = personalInfoList;
        companyList = companyInfoList;
        
        cantonCombo.removeAllItems();
        provinceCombo.removeAllItems();
        districtCombo.removeAllItems();
        phoneCatCombo.removeAllItems();
       
        allProvinces = get_all_procs.get_all_provinces();
        allCategories = get_all_procs.get_all_ph_categories();
        
        for(province prov : allProvinces){
           provinceCombo.addItem(prov.getName_province());
        }
        for(phone_category cat : allCategories){
            phoneCatCombo.addItem(cat.getDescription_category());
        }
        
        String nameProvince = (String) provinceCombo.getSelectedItem();
        allCantons = get_procs.get_cantons_by_province(get_procs.get_province_by_name(nameProvince).getId_province());
        
        String nameCanton = (String) cantonCombo.getSelectedItem();
        allDistricts = get_procs.get_districts_by_canton(get_procs.get_canton_by_name(nameCanton).getId_canton());
        
        for(canton cant : allCantons){
            cantonCombo.addItem(cant.getName_canton());
        }
        for(district dist : allDistricts){
            districtCombo.addItem(dist.getName_district());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        mailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        phoneCatCombo = new javax.swing.JComboBox<>();
        provinceCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cantonCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        districtCombo = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        nextImage = new Utilities.image_avatar();

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(1260, 700));

        jLabel7.setText("Correo");

        mailField.setBorder(null);

        phoneField.setBorder(null);

        jLabel5.setText("Número Teléfono");

        jLabel13.setText("Tipo de teléfono");

        phoneCatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        phoneCatCombo.setBorder(null);

        provinceCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        provinceCombo.setBorder(null);
        provinceCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                provinceComboItemStateChanged(evt);
            }
        });

        jLabel10.setText("Provincia");

        cantonCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cantonCombo.setBorder(null);
        cantonCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cantonComboItemStateChanged(evt);
            }
        });

        jLabel11.setText("Canton");

        jLabel3.setText("Distrito");

        districtCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        districtCombo.setBorder(null);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        nextImage.setBorderSize(0);
        nextImage.setBorderSpace(0);
        nextImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/optionsPerPanel/endImage.png"))); // NOI18N
        nextImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextImageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provinceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(districtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneCatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(nextImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(provinceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addComponent(cantonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(districtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jLabel13)
                .addGap(6, 6, 6)
                .addComponent(phoneCatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(nextImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextImageMouseClicked
        boolean isChanged = false;
        try {
            if (!phoneField.getText().equals("") && !mailField.getText().equals("")) {
                String firstName = (String) infoList.get(0);
                String secondName = (String) infoList.get(1);
                String firstSurname = (String) infoList.get(2);
                String secondSurname = (String) infoList.get(3);
                int ced = (int) infoList.get(4);
                java.sql.Date birthDate = (java.sql.Date) infoList.get(5);
                int idCivilStatus = (int) infoList.get(6);
                int childrenCount = (int) infoList.get(7);

                int idPost = (int) companyList.get(0);
                int idCampus = (int) companyList.get(1);
                int idStatus = (int) companyList.get(2);
                java.sql.Date entryDate = (java.sql.Date) companyList.get(3);

                String district = (String) districtCombo.getSelectedItem();
                int idDistrict = get_procs.get_district_by_name(district).getId_district();

                if (extra_methods.isNumeric(content, phoneField.getText())) {
                    if (phoneField.getText().length() == 8) {
                        if(extra_methods.isValidMail(content, mailField.getText())){
                            
                            //Phone
                            int numberPhone = Integer.parseInt(phoneField.getText());
                            String phoneCat = (String) phoneCatCombo.getSelectedItem();
                            int idCat = get_procs.get_phcat_by_name(phoneCat).getId_category();
                            
                            //Inserts
                            ins_procs.insert_employee(firstName, secondName, firstSurname, secondSurname, ced, entryDate, idCampus, idDistrict, idPost, idStatus,
                            idCivilStatus, birthDate, childrenCount);
                            ins_procs.insert_phone(numberPhone, get_procs.get_employee_by_card(ced).getId_employee(), idCat);
                            ins_procs.insert_email(mailField.getText(), get_procs.get_employee_by_card(ced).getId_employee());
                            isChanged = true;
                        }
                    } else {
                        JOptionPane.showMessageDialog(content, "Tamaño incorrecto \nSe esperan 8 caracteres de tipo entero", "Entrada inválida", JOptionPane.ERROR_MESSAGE);
                    }
                }
                extra_methods.changesAdvice(content, isChanged);
            }else{
                JOptionPane.showMessageDialog(content, "Todos los datos de este panel son obligatorios", "ERROR: Faltan campos de llenar", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(insertContactPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(insertContactPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_nextImageMouseClicked

    private void nextImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextImageMouseEntered
        extra_methods.showSelectedOption(nextImage, 995, 420);
    }//GEN-LAST:event_nextImageMouseEntered

    private void nextImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextImageMouseExited
        extra_methods.resetSelectedOption(nextImage, 1000, 420);
    }//GEN-LAST:event_nextImageMouseExited

    private void provinceComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_provinceComboItemStateChanged
            try {
                cantonCombo.removeAllItems();
                String nameProvince = (String) provinceCombo.getSelectedItem();
                allCantons = get_procs.get_cantons_by_province(get_procs.get_province_by_name(nameProvince).getId_province());
                for(canton cant : allCantons){
                    cantonCombo.addItem(cant.getName_canton());
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(insertContactPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(insertContactPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_provinceComboItemStateChanged

    private void cantonComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cantonComboItemStateChanged
            try {
                districtCombo.removeAllItems();
                String nameCanton = (String) cantonCombo.getSelectedItem();
                allDistricts = get_procs.get_districts_by_canton(get_procs.get_canton_by_name(nameCanton).getId_canton());
                for(district dist : allDistricts){
                    districtCombo.addItem(dist.getName_district());
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(insertContactPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(insertContactPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_cantonComboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cantonCombo;
    private javax.swing.JPanel content;
    private javax.swing.JComboBox<String> districtCombo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField mailField;
    private Utilities.image_avatar nextImage;
    private javax.swing.JComboBox<String> phoneCatCombo;
    private javax.swing.JTextField phoneField;
    private javax.swing.JComboBox<String> provinceCombo;
    // End of variables declaration//GEN-END:variables
}
