/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Employees;

import DataBase.get_all_procs;
import DataBase.get_procs;
import DataBase.upd_procs;
import Models.civil_status;
import Models.employee;
import Utilities.extra_methods;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * 
 * @author Lucas A. Oviedo Castro 
 * <p>
 * Last Modify Date: 06/02/2023.
 * By: Lucas A. Oviedo Castro 
 * <p>
 * JPanel with the View to check the employee personal information.
 */
public class personalInfo extends javax.swing.JPanel {
        ArrayList<civil_status> allCivilStatus;
        employee selectedEmp;
        boolean confirmChanges = false;
        
     /**
     * View Constructor
     * @param selectedEmp ArrayList of employees - the list of selected employees
     * @throws ClassNotFoundException if the class is not found
     * @throws SQLException if there is a problem during data collection
     */
    public personalInfo(employee selectedEmp) throws SQLException, ClassNotFoundException {
        initComponents();
        this.selectedEmp = selectedEmp;
        allCivilStatus = get_all_procs.get_all_civil_status();
        civilStatusCombo.removeAllItems();
        
        for(civil_status st : allCivilStatus){
            civilStatusCombo.addItem(st.getName_status());
        }
        updateFields();
        
    }
    
    /**
     * Update Text Fields and Combo Boxes
     * @throws ClassNotFoundException if the class is not found
     * @throws SQLException if there is a problem during data collection
     */
    private void updateFields() throws SQLException, ClassNotFoundException{
        selectedEmp = get_procs.get_employee(selectedEmp.getId_employee());
        civilStatusCombo.setSelectedItem(get_procs.get_civil_status(selectedEmp.getId_civil_status()).getName_status());
        frstNameField.setText(selectedEmp.getFirst_name());
        scndNameField.setText(selectedEmp.getSecond_name());
        frstSurnameField.setText(selectedEmp.getFirst_surname());
        scndSurnameField.setText(selectedEmp.getSecond_surname());
        idCardField.setText(selectedEmp.getId_card() + "");
        ageField.setText(selectedEmp.getAge() + "");
        childrenCountField.setText(selectedEmp.getChildren_count() + "");
        birthDateChooser.setDate(selectedEmp.getBirth_date());   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        frstNameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();
        idCardField = new javax.swing.JTextField();
        childrenCountField = new javax.swing.JTextField();
        scndSurnameField = new javax.swing.JTextField();
        frstSurnameField = new javax.swing.JTextField();
        scndNameField = new javax.swing.JTextField();
        civilStatusCombo = new javax.swing.JComboBox<>();
        birthDateChooser = new com.toedter.calendar.JDateChooser();
        refreshImage = new Utilities.image_avatar();

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(1260, 700));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("Edad");

        jLabel2.setText("Primer Nombre");

        jLabel3.setText("Segundo Nombre");

        jLabel4.setText("Primer Apellido");

        jLabel5.setText("Segundo Apellido");

        jLabel6.setText("Cédula");

        jLabel7.setText("Estado Civil");

        jLabel8.setText("Hijos");

        jLabel9.setText("Fecha Nacimiento");

        frstNameField.setBorder(null);

        ageField.setBorder(null);
        ageField.setFocusable(false);

        idCardField.setBorder(null);

        childrenCountField.setBorder(null);

        scndSurnameField.setBorder(null);

        frstSurnameField.setBorder(null);

        scndNameField.setBorder(null);

        civilStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        refreshImage.setBorderSize(0);
        refreshImage.setBorderSpace(0);
        refreshImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/optionsPerPanel/refreshImage.png"))); // NOI18N
        refreshImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshImageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scndSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frstSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scndNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCardField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(civilStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(childrenCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(refreshImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(546, 546, 546)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(scndSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel4))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(frstSurnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(scndNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(jLabel5))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel3))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(frstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(idCardField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(civilStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(childrenCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(birthDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(refreshImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshImageMouseClicked
    try {
        if(!selectedEmp.getFirst_name().equals(frstNameField.getText())){
            if(extra_methods.isAlpha(content, frstNameField.getText())){
                if(extra_methods.confirmChanges(content, confirmChanges)){
                    String newFrstName = frstNameField.getText();
                    upd_procs.update_employee_first_name(newFrstName, selectedEmp.getId_employee());
                    confirmChanges = true;
                }  
            }

        }
        if(!selectedEmp.getSecond_name().equals(scndNameField.getText())){  
            if(extra_methods.isAlpha(content, scndNameField.getText())){
                if(extra_methods.confirmChanges(content, confirmChanges)){
                    String newScndName = scndNameField.getText(); 
                    upd_procs.update_employee_second_name(newScndName, selectedEmp.getId_employee());
                    confirmChanges = true;
                }
            }
        }
        if(!selectedEmp.getFirst_surname().equals(frstSurnameField.getText())){    
            if(extra_methods.isAlpha(content, frstSurnameField.getText())){
                if(extra_methods.confirmChanges(content, confirmChanges)){
                    String newFrstSurname = frstSurnameField.getText();  
                    upd_procs.update_employee_first_surname(newFrstSurname, selectedEmp.getId_employee());
                    confirmChanges = true;
                }
            }
        }
        if(!selectedEmp.getSecond_surname().equals(scndSurnameField.getText())){
            if(extra_methods.isAlpha(content, scndSurnameField.getText())){
                if(extra_methods.confirmChanges(content, confirmChanges)){
                    String newScndSurname = scndSurnameField.getText();
                    upd_procs.update_employee_second_surname(newScndSurname, selectedEmp.getId_employee());
                    confirmChanges = true;
                }
            }
        }
        if(extra_methods.idCardCheck(content, idCardField.getText())){
            if(selectedEmp.getId_card() != Integer.parseInt(idCardField.getText())){
                if(extra_methods.confirmChanges(content, confirmChanges)){
                    int newIdCard = Integer.parseInt(idCardField.getText());
                    upd_procs.update_employee_id_card(newIdCard, selectedEmp.getId_employee());
                    confirmChanges = true;
                }
            }
        }
        if(!get_procs.get_civil_status(selectedEmp.getId_civil_status()).getName_status().equals(civilStatusCombo.getSelectedItem())){
            if(extra_methods.confirmChanges(content, confirmChanges)){
                String nameCivilStatus = (String) civilStatusCombo.getSelectedItem();
                civil_status selectedStatus = get_procs.get_civil_status_by_name(nameCivilStatus);
                upd_procs.update_employee_civil_status(selectedStatus.getId_civil_status(), selectedEmp.getId_employee());
                confirmChanges = true;
            }
        }
        if(extra_methods.isNumeric(content, childrenCountField.getText())){
            if(selectedEmp.getChildren_count() != Integer.parseInt(childrenCountField.getText())){
                if(extra_methods.confirmChanges(content, confirmChanges)){
                    int newChildrenCount = Integer.parseInt(childrenCountField.getText());
                    upd_procs.update_employee_children_count(newChildrenCount, selectedEmp.getId_employee());
                    confirmChanges = true;
                }
            }
        }
        if(!selectedEmp.getBirth_date().equals(birthDateChooser.getDate())){
            if(extra_methods.confirmChanges(content, confirmChanges)){
                long d = birthDateChooser.getDate().getTime();
                java.sql.Date newDate = new java.sql.Date(d);
                upd_procs.update_employee_birth_date(newDate, selectedEmp.getId_employee());
                confirmChanges = true;
            }
        }
        extra_methods.changesAdvice(content, confirmChanges);
        updateFields();
        confirmChanges = false;
    
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(personalInfo.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
                Logger.getLogger(personalInfo.class.getName()).log(Level.SEVERE, null, ex);
    }  
    }//GEN-LAST:event_refreshImageMouseClicked

    private void refreshImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshImageMouseEntered
        extra_methods.showSelectedOption(refreshImage, 995, 420);
    }//GEN-LAST:event_refreshImageMouseEntered

    private void refreshImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshImageMouseExited
        extra_methods.resetSelectedOption(refreshImage, 1000, 420);
    }//GEN-LAST:event_refreshImageMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private com.toedter.calendar.JDateChooser birthDateChooser;
    private javax.swing.JTextField childrenCountField;
    private javax.swing.JComboBox<String> civilStatusCombo;
    private javax.swing.JPanel content;
    private javax.swing.JTextField frstNameField;
    private javax.swing.JTextField frstSurnameField;
    private javax.swing.JTextField idCardField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private Utilities.image_avatar refreshImage;
    private javax.swing.JTextField scndNameField;
    private javax.swing.JTextField scndSurnameField;
    // End of variables declaration//GEN-END:variables
}
