/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Views.Employees.showEmp;
import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;

import Utilities.extra_methods;
import Views.Employees.insertPersonalPanel;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;

/**
 * 
 * @author Lucas A. Oviedo Castro 
 * <p>
 * Last Modify Date: 06/02/2023.
 * By: Lucas A. Oviedo Castro 
 * <p>
 * JPanel with the Dashboard structure, it has a Content Panel to show other panels
 */
public class Dashboard extends javax.swing.JFrame {
    
    /**
     * View Constructor
     * @throws MessagingException if occurs an error with the transport
     * @throws ClassNotFoundException if the class is not found
     * @throws SQLException if there is a problem during data collection
     */
    public Dashboard() throws SQLException, ClassNotFoundException, MessagingException {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("images/icons8-user-shield-48.png"));
        this.setIconImage(icon);

        setTitle("Control de Personal - PsicoSecurity");
        init_styles();
        showEmp p = new showEmp();
        extra_methods.showPanel(p,content);
        
    }
    
    /**
     * Methods to init the styles
     */
    private void init_styles(){
        headerText.putClientProperty("FlatLaf.style", "font: $h1.font");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        menus = new keeptoo.KGradientPanel();
        employeesImage = new Utilities.image_avatar();
        insertImage = new Utilities.image_avatar();
        configImages = new Utilities.image_avatar();
        logImage = new Utilities.image_avatar();
        closeImage = new Utilities.image_avatar();
        header = new keeptoo.KGradientPanel();
        headerText = new javax.swing.JLabel();
        appIconHeader = new Utilities.image_avatar();
        positionImage = new Utilities.image_avatar();
        openImage = new Utilities.image_avatar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(1100, 800));
        bg.setPreferredSize(new java.awt.Dimension(800, 800));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        menus.setkEndColor(new java.awt.Color(255, 195, 255));
        menus.setkGradientFocus(100);
        menus.setkStartColor(new java.awt.Color(155, 225, 247));
        menus.setPreferredSize(new java.awt.Dimension(70, 360));

        employeesImage.setBorderSize(0);
        employeesImage.setBorderSpace(2);
        employeesImage.setGradientColor1(new java.awt.Color(153, 0, 153));
        employeesImage.setGradientColor2(new java.awt.Color(102, 102, 255));
        employeesImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/menuBarTop/searchEmployees.png"))); // NOI18N
        employeesImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeesImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeesImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeesImageMouseExited(evt);
            }
        });

        insertImage.setBorderSize(0);
        insertImage.setBorderSpace(2);
        insertImage.setGradientColor1(new java.awt.Color(153, 0, 153));
        insertImage.setGradientColor2(new java.awt.Color(102, 102, 255));
        insertImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/menuBarTop/addEmployee.png"))); // NOI18N
        insertImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                insertImageMouseExited(evt);
            }
        });

        configImages.setBorderSize(0);
        configImages.setBorderSpace(1);
        configImages.setGradientColor1(new java.awt.Color(153, 0, 153));
        configImages.setGradientColor2(new java.awt.Color(102, 102, 255));
        configImages.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/menuBarTop/addSpacesDB.png"))); // NOI18N
        configImages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configImagesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configImagesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configImagesMouseExited(evt);
            }
        });

        logImage.setBorderSize(0);
        logImage.setBorderSpace(2);
        logImage.setGradientColor1(new java.awt.Color(153, 0, 153));
        logImage.setGradientColor2(new java.awt.Color(102, 102, 255));
        logImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/menuBarTop/log.png"))); // NOI18N
        logImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logImageMouseExited(evt);
            }
        });

        closeImage.setBorderSize(0);
        closeImage.setFocusCycleRoot(true);
        closeImage.setGradientColor1(new java.awt.Color(153, 0, 153));
        closeImage.setGradientColor2(new java.awt.Color(102, 102, 255));
        closeImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/menuBarTop/menu.png"))); // NOI18N
        closeImage.setInheritsPopupMenu(true);
        closeImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeImageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menusLayout = new javax.swing.GroupLayout(menus);
        menus.setLayout(menusLayout);
        menusLayout.setHorizontalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeesImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configImages, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        menusLayout.setVerticalGroup(
            menusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menusLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(closeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(employeesImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(insertImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(configImages, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(logImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        header.setkEndColor(new java.awt.Color(255, 195, 255));
        header.setkGradientFocus(1200);
        header.setkStartColor(new java.awt.Color(155, 225, 247));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headerText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerText.setText("  PsicoSecurity");
        header.add(headerText, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 280, 65));

        appIconHeader.setBorderSize(0);
        appIconHeader.setFocusCycleRoot(true);
        appIconHeader.setGradientColor1(new java.awt.Color(153, 0, 153));
        appIconHeader.setGradientColor2(new java.awt.Color(102, 102, 255));
        appIconHeader.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-shield-48.png"))); // NOI18N
        appIconHeader.setInheritsPopupMenu(true);
        appIconHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appIconHeaderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appIconHeaderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appIconHeaderMouseExited(evt);
            }
        });
        header.add(appIconHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 90, 70));

        positionImage.setBorderSize(0);
        positionImage.setBorderSpace(0);
        positionImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/menuBarTop/actualPosition.png"))); // NOI18N
        header.add(positionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, 30, 30));

        openImage.setBorderSize(0);
        openImage.setFocusCycleRoot(true);
        openImage.setGradientColor1(new java.awt.Color(153, 0, 153));
        openImage.setGradientColor2(new java.awt.Color(102, 102, 255));
        openImage.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/menuBarTop/menu.png"))); // NOI18N
        openImage.setInheritsPopupMenu(true);
        openImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                openImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                openImageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(openImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(openImage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void employeesImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesImageMouseEntered
        extra_methods.showSelectedOption(employeesImage, 5,90);
    }//GEN-LAST:event_employeesImageMouseEntered

    private void employeesImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesImageMouseExited
        extra_methods.resetSelectedOption(employeesImage, 10,90);
    }//GEN-LAST:event_employeesImageMouseExited

    private void insertImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertImageMouseEntered
        extra_methods.showSelectedOption(insertImage, 5, 157);
    }//GEN-LAST:event_insertImageMouseEntered

    private void insertImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertImageMouseExited
        extra_methods.resetSelectedOption(insertImage, 10, 157);
    }//GEN-LAST:event_insertImageMouseExited

    private void configImagesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configImagesMouseEntered
        extra_methods.showSelectedOption(configImages, 5, 227);
    }//GEN-LAST:event_configImagesMouseEntered

    private void configImagesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configImagesMouseExited
        extra_methods.resetSelectedOption(configImages, 10, 227);
    }//GEN-LAST:event_configImagesMouseExited

    private void logImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logImageMouseEntered
       extra_methods.showSelectedOption(logImage, 5, 297);
    }//GEN-LAST:event_logImageMouseEntered

    private void logImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logImageMouseExited
        extra_methods.resetSelectedOption(logImage, 10, 297);
    }//GEN-LAST:event_logImageMouseExited

    private void employeesImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeesImageMouseClicked
        try {
            showEmp p = new showEmp();        
            extra_methods.showPanel(p,content);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_employeesImageMouseClicked

    private void insertImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertImageMouseClicked
        try {
            insertPersonalPanel p = new insertPersonalPanel();
            extra_methods.showPanel(p, content);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insertImageMouseClicked

    private void configImagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configImagesMouseClicked
        try {
            insertData p = new insertData();
            extra_methods.showPanel(p, content);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_configImagesMouseClicked

    private void logImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logImageMouseClicked
        try {
            logPanel p = new logPanel();
            extra_methods.showPanel(p, content);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logImageMouseClicked

    int x = 70;
    private void closeImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeImageMouseClicked
        if (x == 70){
            menus.show();
            menus.setSize(70, 360);
            Thread th = new Thread() {
                @Override
                public void run(){
                    try{
                        for (int i = 70; i >= 0; i--){
                            Thread.sleep(1);
                            menus.setSize(i, 360);
                    }
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }; th.start();
        x = 0;
        }
    }//GEN-LAST:event_closeImageMouseClicked

    private void closeImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeImageMouseEntered
        extra_methods.showSelectedOption(closeImage, 5, 20);
    }//GEN-LAST:event_closeImageMouseEntered

    private void closeImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeImageMouseExited
        extra_methods.resetSelectedOption(closeImage, 10, 20);
    }//GEN-LAST:event_closeImageMouseExited

    private void openImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openImageMouseClicked
        if (x == 0){
            menus.show();
            menus.setSize(x, 360);
            Thread th = new Thread() {
                @Override
                public void run(){
                    try{
                        for (int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            menus.setSize(i, 360);
                    }
                } catch (Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }; th.start();
        x = 70;
        }
    }//GEN-LAST:event_openImageMouseClicked

    private void openImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openImageMouseEntered
        extra_methods.showSelectedOption(openImage, 15, 270);
    }//GEN-LAST:event_openImageMouseEntered

    private void openImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openImageMouseExited
        extra_methods.resetSelectedOption(openImage, 20, 270);
    }//GEN-LAST:event_openImageMouseExited

    private void appIconHeaderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appIconHeaderMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_appIconHeaderMouseExited

    private void appIconHeaderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appIconHeaderMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_appIconHeaderMouseEntered

    private void appIconHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appIconHeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_appIconHeaderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    FlatLightFlatIJTheme.setup();
                    new Dashboard().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MessagingException ex) {
                    Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public static void movePosition(int x, int y){
        menus.add(positionImage);
        positionImage.setLocation(x,y);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Utilities.image_avatar appIconHeader;
    private javax.swing.JPanel bg;
    private Utilities.image_avatar closeImage;
    public static Utilities.image_avatar configImages;
    static javax.swing.JPanel content;
    public static Utilities.image_avatar employeesImage;
    private keeptoo.KGradientPanel header;
    private javax.swing.JLabel headerText;
    public static Utilities.image_avatar insertImage;
    public static Utilities.image_avatar logImage;
    private static keeptoo.KGradientPanel menus;
    private Utilities.image_avatar openImage;
    public static Utilities.image_avatar positionImage;
    // End of variables declaration//GEN-END:variables
}
